{% set version = "0.6.0" %}

package:
  name: maya
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/maya/maya-{{ version }}.tar.gz
  sha256: 37ee82c48704db941313bcb74defcbb3394578787475072821b789751b683eeb

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - humanize
    - pytz
    - dateparser >=0.7.0
    - tzlocal
    - pendulum >=2.0.2
    - snaptime

test:
  imports:
    - maya

about:
  home: https://github.com/kennethreitz/maya
  license: MIT
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: 'Datetimes for Humans'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
