{% set version = "0.6.1" %}

package:
  name: maya
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/maya/maya-{{ version }}.tar.gz
  sha256: 7f53e06d5a123613dce7c270cbc647643a6942590dba7a19ec36194d0338c3f4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - humanize
    - pytz
    - dateparser >=0.7.0, !=1.1.0
    - tzlocal
    - pendulum >=2.0.2
    - snaptime

test:
  imports:
    - maya

about:
  home: https://github.com/kennethreitz/maya
  license: MIT
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: 'Datetimes for Humans'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
