{% set version = "0.3.3" %}

package:
  name: maya
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/maya/maya-{{ version }}.tar.gz
  sha256: bad39d8f9c6e2c8f446a2187eafbc2128aa20397787be1e4697bb29b239908f5

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - humanize
    - pytz
    - dateparser
    - ruamel.yaml
    - tzlocal
    - pendulum

test:
  imports:
    - maya

about:
  home: https://github.com/kennethreitz/maya
  license: MIT
  # license_file: LICENSE
  summary: 'Datetimes for Humans.'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
