{% set version = "0.3.4" %}

package:
  name: maya
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/maya/maya-{{ version }}.tar.gz
  sha256: d8a7ed8513b2990036fe456c9f595b54d19ec49cb4461cd95a2ef6c487fb55eb

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - humanize
    - pytz
    - dateparser
    - ruamel.yaml
    - tzlocal
    - pendulum

test:
  imports:
    - maya

about:
  home: https://github.com/kennethreitz/maya
  license: MIT
  # license_file: LICENSE
  summary: 'Datetimes for Humans.'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
