{% set version = "0.4.1" %}

package:
  name: maya
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/maya/maya-{{ version }}.tar.gz
  sha256: 452e5812c3d5f936a6c8cbea7fc717dcf3ea86d8e58aecb7a057f5f6535dd92e

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - humanize
    - pytz
    - dateparser >=0.7.0
    - tzlocal
    - pendulum >=1.0,<=1.5.1
    - snaptime

test:
  imports:
    - maya

about:
  home: https://github.com/kennethreitz/maya
  license: MIT
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: 'Datetimes for Humans'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
