{% set version = "0.3.3" %}

package:
  name: maya
  version: {{ version }}

source:
  fn: maya-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/maya/maya-0.3.3.tar.gz
  sha256: bad39d8f9c6e2c8f446a2187eafbc2128aa20397787be1e4697bb29b239908f5
  patches:
    - win_encoding.patch  # [win and py3k]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - humanize
    - pytz
    - dateparser
    - iso8601
    - python-dateutil
    - ruamel.yaml
    - tzlocal

test:
  imports:
    - maya

about:
  home: https://github.com/kennethreitz/maya
  license: MIT
  license_file: LICENSE
  summary: 'Datetimes for Humans.'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
