travis:
  secure:
    BINSTAR_TOKEN: hOgJ7EGsfeMU1iXYhQCehB+vqcKcuY3Vufan3QDjMREMaRToSi59SZXIfPS5MGfrAAfuOvUduLFNu/8hqxAT/9svqyG00RWZMctd4TZqU+6iSZsE8CVun+uij9O4pJgnvnQb3Ipsh9A+PR8qTp5nBjcW2DMK/CnMcx/lHeKlzHoqHdqRbTdHnuOqBAWJc6eFFAOWlM8o1oi4L/45mjPdf2bIOYgRNuUFXUSLbBjJqwFJy5SwE40DUFOiaJqRx44gjYq0Gg5xNOHDN2rSXm4lOttFElOMRsyAw6IEEEF44WDzIDh5epgrDzk2V6sRqTyD9YMHQYJdT69pMWdIFjC/yZQYJ2AaXmLE6GFG9oqJw2H1kzlZ83tJI7kiaFVlfF/zz/G1xfj2tHXtiWikJdossCDFZkSgOY2T4bfm55uhChzp2vYKNUTbfVT/hy/UpwiMPuuE2nsH9rqvsRmENvE0IIVQgNSXhGFR6R8n0B1BEeEfUlyNKilsH2PN85R7i8GmJ6NgSum6LUzGKQlILISyPFjDbzlfdK/tvXqBkxvZdBxEeS26lN9V5EBAciZJDNdbKY7/DRc59PWG+xkTx2YhWGE/C9v5fNZVYUH5rOdCCWyG8B8DpcT3rJmhV+WqbM1s1MELDE1l3HIDdIeYkky6NFbYj/CRXtjMTSrEzNcCBk8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
